blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/anse-app/chatgpt-demo/discussions
    about: Use discussions if you have an idea for improvement or for asking questions.